# Generated by Django 4.2.5 on 2023-09-27 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0003_alter_projects_options_alter_projects_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Interfaces",
            fields=[
                (
                    "id",
                    models.AutoField(
                        help_text="id主键描述",
                        primary_key=True,
                        serialize=False,
                        verbose_name="id主键",
                    ),
                ),
                (
                    "creat_time",
                    models.DateTimeField(
                        auto_now_add=True, help_text="创建时间描述", verbose_name="创建时间"
                    ),
                ),
                (
                    "update_time",
                    models.DateTimeField(
                        auto_now=True, help_text="更新时间描述", verbose_name="更新时间"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="接口名称描述",
                        max_length=20,
                        unique=True,
                        verbose_name="接口名称",
                    ),
                ),
                (
                    "tester",
                    models.CharField(
                        help_text="测试人员描述", max_length=10, verbose_name="测试人员"
                    ),
                ),
                (
                    "projects",
                    models.ForeignKey(
                        help_text="所属项目描述",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.projects",
                        verbose_name="所属项目",
                    ),
                ),
            ],
            options={
                "verbose_name": "接口表",
                "verbose_name_plural": "接口表描述",
                "db_table": "tb_interfaces",
            },
        ),
    ]
